# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 23:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DBServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=144)),
                ('username', models.CharField(max_length=144)),
                ('password', models.CharField(max_length=144)),
            ],
        ),
        migrations.AlterField(
            model_name='table',
            name='db_server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etl.DBServer'),
        ),
    ]
