# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0002_auto_20171002_2355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dbserver',
            options={'verbose_name': 'DBServer'},
        ),
        migrations.AddField(
            model_name='table',
            name='raw_file',
            field=models.FileField(default='/N', upload_to=b''),
            preserve_default=False,
        ),
    ]
