# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0004_auto_20171004_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='export_file',
            field=models.FileField(default='/N', upload_to=b''),
            preserve_default=False,
        ),
    ]
