# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 20:48
from __future__ import unicode_literals

from django.db import migrations, models
import etl_site.etl.models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0005_table_export_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='export_file',
        ),
        migrations.AddField(
            model_name='table',
            name='sql_file',
            field=models.FileField(default='/n', upload_to=etl_site.etl.models.sql_attachment_path),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='table',
            name='raw_file',
            field=models.FileField(upload_to='static/documents/raw/ef2a1c2b-52a6-4514-970b-ebd3200efa66/'),
        ),
    ]
